--create table Funcionario(
--IdFunc int identity(1,1),
--Nome varchar(200),
--Apelido varchar(30),
--Senha varchar(100),
--Telefone char(12),
--Condicao varchar(8) default 'ativo'
--constraint pk_IdFunc primary key (idFunc)
--)